fix(ci): use yq

diff --git a/.github/workflows/check_bootnodes_enrs.yml b/.github/workflows/check_bootnodes_enrs.yml
--- a/.github/workflows/check_bootnodes_enrs.yml
+++ b/.github/workflows/check_bootnodes_enrs.yml
@@ -50,27 +50,24 @@ jobs:
       - name: Check ENR Strings with enr-cli
         run: |
           for FILE in $(find . -type f \( -name 'bootnodes.yaml' -o -name 'bootstrap_nodes.txt' \)); do
-            echo "Testing decoding in file: $FILE"
+            echo "Processing file: $FILE"
+            if [[ "$FILE" == *".yaml" ]]; then
+              LINES=$(yq eval '.[] | select(test("enr:"))' "$FILE")
+            elif [[ "$FILE" == *".txt" ]]; then
+              LINES=$(grep -E '^[[:space:]]*enr:.*' "$FILE" | grep -v -E '^[[:space:]]*(#|$)')
+            else
+              echo "Unsupported file type: $FILE"
+              exit 1
+            fi
+
             while IFS= read -r LINE; do
-              if [[ "$LINE" =~ enr: ]]; then
-                if [[ "$FILE" == *".yaml" ]]; then
-                  BASE64_STRING=${LINE#enr:}
-                elif [[ "$FILE" == *".txt" ]]; then
-                  BASE64_STRING=$(echo "$LINE" | grep -o 'enr:.*')
-                else
-                  echo "Unsupported file type: $FILE"
+              if [[ -n "$LINE" && "$LINE" =~ enr: ]]; then
+                echo "Processing line: $LINE"
+                enr-cli read "$LINE" 1>/dev/null
+                if [ $? -ne 0 ]; then
+                  echo "Error: enr-cli read failed for line: $LINE in file: $FILE"
                   exit 1
                 fi
-
-                BASE64_STRING=$(echo "$BASE64_STRING" | awk '{gsub(/"/, "", $0); print}')
-                if [[ -n "$BASE64_STRING" ]]; then
-                  echo "Testing decoding of enr:$BASE64_STRING"
-                  enr-cli read "$BASE64_STRING" 1>/dev/null
-                  if [ $? -ne 0 ]; then
-                    echo "Error: ENR could not be decoded in $FILE: enr:$BASE64_STRING"
-                    exit 1
-                  fi
-                fi
               fi
-            done < "$FILE"
+            done <<< "$LINES"
           done
