feat(ci): add decode base64 check

diff --git a/.github/workflows/check_bootnodes_enrs.yml b/.github/workflows/check_bootnodes_enrs.yml
--- a/.github/workflows/check_bootnodes_enrs.yml
+++ b/.github/workflows/check_bootnodes_enrs.yml
@@ -35,3 +35,37 @@ jobs:
             echo "$files_with_padding"
             exit 1
           fi
+
+      - name: Check base64 decoding
+        run: |
+          files_with_decoding_issue=""
+
+          for FILE in $(find . -type f \( -name 'bootnodes.yaml' -o -name 'bootstrap_nodes.txt' \)); do
+            echo "Testing decoding in file: $FILE"
+            while read -r LINE; do
+              if [[ "$LINE" =~ enr: ]]; then
+                ENR_LINE=$(echo "$LINE" | sed -e 's/#.*//' -e 's/^[ \t]*//' -e 's/[ \t]*$//')
+
+                if [[ "$ENR_LINE" =~ ^- ]]; then
+                  BASE64_STRING=$(echo "$ENR_LINE" | awk -F "enr:" '{print $2}' | awk '{$1=$1; gsub(/\"/, "", $0); print}')
+                else
+                  BASE64_STRING=${ENR_LINE#enr:}
+                  BASE64_STRING=$(echo "$BASE64_STRING" | awk '{$1=$1; gsub(/\"/, "", $0); print}')
+                fi
+
+                base64 -d <<< "$BASE64_STRING" 1>/dev/null
+                if [ $? -ne 0 ]; then
+                  if [[ "$files_with_decoding_issue" != *"$FILE"* ]]; then
+                    echo "Error: ENR could not be decoded in $FILE: enr:$BASE64_STRING"
+                    files_with_decoding_issue="$files_with_decoding_issue $FILE"
+                  fi
+                fi
+              fi
+            done < "$FILE"
+          done
+
+          if [ -n "$files_with_decoding_issue" ]; then
+            echo "Error: Bootnodes ENR strings have decoding issues in the following files:"
+            echo "$files_with_decoding_issue"
+            exit 1
+          fi
